Implement root tasks
vercel/turborepo pull request #1040
Opened 2022-04-12 00:07 UTC by gsoltis

Adds the ability to run tasks from the root `package.json` file.

Implementation notes that will need to be documented:
 * Tasks run from the root are opt-in. That is, `turbo.json`*must* have an entry for `_root#<task>` to enable running that task at the root.
 * `_root` is available in filters, so `turbo run my-task --filter=_root` will run `_root#my-task`. 
 * If an entry exists in `turbo.json` for `_root#task`, then `turbo run task` will also run that task for the root.
 * There is some best-effort cycle detection in place. If the root `package.json` has `"build": "turbo run build"`, then even after opting in, `turbo run build --filter=_root` will produce an error. This cycle detection can be circumvented with aliases or other indirection used to run `turbo`.
 * For the purposes of changed files, any changed file in a repo that doesn't belong to another package is considered to belong to the root.
   * Note that this could cause frequent runs of root tasks if they are triggered from git changes. With `inputs` specified, they should hit cache if nothing relevant has changed.

Additional changes:
 * `e2e` tests now include a root task
 * a package task is now sufficient to mark a particular task as runnable by `turbo`. e.g. if you defined `foo#my-task` but not `my-task` in `turbo.json`, previously running `turbo run my-task` would be an error, now it will run `foo#my-task`.

Fixes #845

2022-04-12 17:23 UTC, jaredpalmer requested changes

2022-04-12 17:23 UTC, jaredpalmer commented on cli/internal/scope/filter/filter.go
> +						return nil, fmt.Errorf("failed to resolve directory relativeeship %v contains %v: %v", parentDir, r.Cwd, err)
Fix error message here

2022-04-12 17:23 UTC, jaredpalmer commented on cli/internal/scope/filter/filter.go
> +					//if parentDir == r.Cwd {
```suggestion
```

2022-04-12 18:10 UTC, gsoltis commented
Windows `e2e` test is still broken, so not quite ready for merge yet

2022-04-19 21:28 UTC, foogazy commented
Hello! This would be huge! How can we help for this to be merged?

2022-04-20 00:02 UTC, gsoltis commented
@foogazy thanks for your interest!

This is coming soon, although there may be some slight tweaks. 

The most helpful thing would be to verify that it works for your use cases.

2022-04-22 11:20 UTC, foogazy commented
@gsoltis Hello! Thank you so much for all your amazing work! 

Sure! I tested on my system at can verify it works fine: 

System details: 

- Macbook Pro - MacOS Monterey - M1 Chip - 16GB Memory 
- Node v. 16 
- Yarn 1.22.18
- npm 8.3.1

Hope this helps. :)

2022-04-25 21:59 UTC, gsoltis commented
@foogazy Awesome, glad to hear it!

2022-05-17 09:37 UTC, dagda1 commented
Oh man, I wish this was merged.

2022-05-17 16:31 UTC, merged

2022-07-02 03:11 UTC, trevorr commented
@gsoltis Does this support referencing root package-tasks in `dependsOn`? When I try that with v1.3.1, I get `error preparing engine: found reference to unknown package: //`.