Change Berry's `cacheKey` to be a string
vercel/turborepo pull request #2102
Opened 2022-09-28 11:40 UTC by amitdahan

# Summary

Closes #2101

2022-09-28 16:17 UTC, chris-olszewski requested changes
Thanks for fixing this! Just some small fixup needed before merging.

2022-09-28 16:17 UTC, chris-olszewski commented on cli/internal/lockfile/berry_lockfile.go
> +	cacheKey := "-1"
Now that we're using a string for `cacheKey` lets use `""` as the empty value.
```suggestion
	cacheKey := ""
```

2022-09-28 17:43 UTC, chris-olszewski approved these changes

2022-09-28 17:44 UTC, merged

2022-09-29 06:14 UTC, amitdahan commented
Thanks @chris-olszewski !