fix(examples): inject react runtime for ui package
vercel/turborepo pull request #371
Opened 2021-12-20 19:11 UTC by tknickman

### What has been changed?
1. Update `build` and `dev` command for `kitchen-sink` examples ui package to support components that don't explicitly import `React`.

### Why?
Starting from React 17, React shipped with the new [JSX Transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html), allowing components to include JSX without React being in scope (For example, the `Button` component included below). Because of this, it is now very common to write react components without explicitly importing React at all.

However, in the current `kitchen-sink` example, doing this will break, and throw:
`ReferenceError: React is not defined`.

### How?
In order to support this common use case, we need to instruct `tsup` to inject the `react` runtime into the build. Because `tsup` uses `esbuild`, we can leverage [--inject](https://esbuild.github.io/api/#inject) to automatically replace a global variable with an import from another file. tsup has supported this argument (although poorly documented) since 5.3.0 ([commit](https://github.com/egoist/tsup/commit/f268c649d2ed863aeeb7e77070cab681d2ae8765))

#### Other
* The [esbuild docs cover the exact scenario](https://esbuild.github.io/content-types/#auto-import-for-jsx) this PR is fixing for this example!
* An [issue was raised](https://github.com/egoist/tsup/issues/390) against tsup to support the inject flag to solve this problem as well

Fixing this will hopefully avoid frustration from new users who want to use an example as a starting point, with minimal changes to the build configuration.

2021-12-20 20:08 UTC, jaredpalmer commented on examples/kitchen-sink/packages/ui/src/Button/index.tsx
> +export const Button = ({ children, ...other }) => {
Rename to just Button.tsx

2021-12-20 20:10 UTC, jaredpalmer requested changes
Looks, good, just let's get rid of index.tsx's / barrel files aside from the root in `ui`.

2021-12-20 20:10 UTC, jaredpalmer commented on examples/kitchen-sink/packages/ui/src/CounterButton/index.tsx
> +export const CounterButton = () => {
Move to ./src/CounterButton.tsx

2021-12-20 20:11 UTC, jaredpalmer commented on examples/kitchen-sink/packages/ui/src/Button/index.tsx
> +export const Button = ({ children, ...other }) => {
Move to ./src/Button.tsx

2021-12-21 16:11 UTC, tknickman commented
@jaredpalmer good call, updated with your suggestions! Thanks!

2021-12-23 15:27 UTC, jaredpalmer approved these changes

2021-12-23 15:28 UTC, merged