fix(ecmascript): eval assignop to the ident
vercel/turborepo pull request #4609
Opened 2023-04-17 17:26 UTC by kwonoj

### Description

- closes WEB-889

When there is a variable with `+=` assignop only to the given ident

```
var css = '';
for (var i = 0; i < length; i++) {
        var partRule = this.rules[i];

        if (typeof partRule === 'string') {
          css += partRule;
        } else if (partRule) {
         css += partString;
        }
      }

      if (css) {
       ....
      }
```

evaluated result becomes

```
var css = '';
for(var i = 0; i < length; i++){
    var partRule = this.rules[i];
    if (typeof partRule === 'string') {
        css += partRule;
    } else if (partRule) {
        css += partString;
    }
}
if ("TURBOPACK compile-time falsy", 0) {
    "TURBOPACK unreachable";
}
```

so `if (css)` condition never executed even though it can be executed depends on the runtime assignop condition. 

PR attempts to evaluate if assignop is for the ident to prevent this.

2023-04-18 07:11 UTC, sokra requested changes
Could you add a test case to tests/analyzer/graph?

The fix doesn't look right to me...

2023-04-18 07:22 UTC, kwonoj commented
@sokra Not sure how to translate test outputs to confirm if this is incorrect approach: https://github.com/vercel/turbo/pull/4609/commits/6dba17d19e2d524ff2323a144942f21ce2093d39

2023-04-18 12:57 UTC, sokra commented on crates/turbopack-ecmascript/tests/analyzer/graph/assign/input.js
> +}
```
let a = "";
a += "x";

let b = 0;
b -= 1;

let c = 0;
c++;

let d = 0;
d ||= 1;

let e = 1;
e &&= 2;
```

should resolve as:

```
a = "" | a + "x"
b = 0 | b - 1
c = 0 | c + 1
d = 0 | 1
e = 1 | 2
```

2023-04-20 00:48 UTC, kdy1 approved these changes

2023-04-20 00:51 UTC, kdy1 commented on crates/turbopack-ecmascript/src/analyzer/graph.rs
> +                        self.add_value(key.to_id(), value);
This should not be `add_value`, I think, because for

```ts
a = 1
a += 1 
```

`a` is 2, not 1

2023-04-20 13:39 UTC, sokra approved these changes

2023-04-20 14:00 UTC, merged