feat: turbo bin
vercel/turborepo pull request #561
Opened 2022-01-14 15:47 UTC by Xenfo

closes #511

## What this PR brings:
Implements `turbo bin` which prints out the path to Turbo's binary.

2022-01-14 15:52 UTC, jaredpalmer requested changes
Looks good. Can we update docs too?

2022-01-25 14:21 UTC, Xenfo commented
It's not PNPM specific, it happens with all of the backends.

2022-02-05 01:00 UTC, gsoltis commented
Test flakiness was unrelated

2022-02-05 01:00 UTC, gsoltis approved these changes

2022-02-05 01:19 UTC, jaredpalmer approved these changes

2022-02-05 01:20 UTC, merged