Add `schema.json` to have a better IDE intellisense
vercel/turborepo pull request #634
Opened 2022-01-28 19:17 UTC by arthurfiorette

This PR adds an `schema.d.ts` file with all _(documented ones)_ properties in the `turbo.json` file. This way, and combining with the new `npm run jsonschema` script, it's possible to generate an [Json schema](https://json-schema.org/) file.

I configured to the generated file be placed at `docs/public/schema.json` , so it can be requested from the url `https://turborepo.org/schema.json`. You can test how powerfull it is with in IDE autocompletion, intellisense and inline documentation.

_Try it out in your IDE by adding `"$schema": "./docs/public/schema.json"`_

![image](https://user-images.githubusercontent.com/47537704/151606809-3adf3967-4b66-4ea0-8d61-02f468d9215f.png)

It also updated all _(that i saw :P)_ documentation examples to include the `$schema` property, this way, it will go by default for all `Ctrl C/V` users out there.

But i still need to point out some things:

- As the `jsonschema` _(Is that even a good name?)_ script is going to be ran a lot, may we add `ts-json-schema-generator` to the `devDependencies` group?
- In the root `turbo.json` file, i saw an `env` property, but it is not documented, should i add it or it just shouldn't be there?
- I am not a native english speaker, even that i mostly copy pasted the tsdocs in the `schema.d.ts` file, it is not perfect and it probably has some typos.

That's it for now. Thanks for this amazing package!

2022-01-28 19:21 UTC, arthurfiorette commented
https://turbo-site-git-fork-arthurfiorette-main.vercel.sh/schema.json

2022-01-31 17:03 UTC, jaredpalmer commented on schema.d.ts
> +  npmClient?: "yarn" | "npm" | "pnpm";
no longer supported / should be removed.

2022-02-01 11:48 UTC, arthurfiorette commented
@jaredpalmer anything more?

2022-02-02 17:29 UTC, pivoamrl reviewed
thats nice!

2022-02-08 20:38 UTC, jaredpalmer requested changes

2022-02-08 20:38 UTC, jaredpalmer commented on docs/public/schema.json
> +        "npmClient": {
Remove

2022-02-08 20:40 UTC, jaredpalmer requested changes
Let's move everything into `docs` folder since this is essentially part of documentation at the moment because it is not directly derived from actual source code

2022-02-08 20:40 UTC, jaredpalmer commented on schema.d.ts
> +   * Any other entry* without this prefix, will be considered filesystem glob. The
why is there a *?

2022-02-08 20:40 UTC, jaredpalmer commented on schema.d.ts
> +   * Any other entry* without this prefix, will be considered filesystem glob. The
Let's move this file into `docs`

2022-02-09 17:50 UTC, jaredpalmer approved these changes

2022-02-09 21:21 UTC, merged