feat: basic exclude for scope
vercel/turborepo pull request #696
Opened 2022-02-08 03:15 UTC by Xenfo

Add basic excluding while the `--filter` flag is being developed.

2022-02-08 13:58 UTC, jaredpalmer requested changes

2022-02-08 14:19 UTC, Xenfo commented on cli/internal/run/run.go
> +		if strings.HasPrefix(pattern, "-") {
Ok will do.

2022-02-08 16:54 UTC, jaredpalmer commented
Can you also add e2e tests?

2022-02-11 18:54 UTC, jaredpalmer approved these changes

2022-02-11 19:07 UTC, merged