feat: add support for JSON with comments `turbo.json` file
vercel/turborepo pull request #745
Opened 2022-02-16 02:25 UTC by weyert

Allow the `turbo.json` file to contain comments

Makes it easier to explain the pipeline when they are quite large :)

2022-02-16 03:40 UTC, weyert commented
@gsoltis I am not sure why the benchmark build step is failing

2022-02-16 15:55 UTC, jaredpalmer requested changes

2022-02-16 15:55 UTC, jaredpalmer commented on cli/internal/fs/package_json.go
> +	// b, err := ioutil.ReadFile(path)
Remove comments

2022-02-16 17:38 UTC, weyert commented on cli/internal/fs/package_json.go
> +	// b, err := ioutil.ReadFile(path)
Removed them

2022-02-16 23:05 UTC, gsoltis approved these changes

2022-02-17 20:10 UTC, weyert commented
Any more changes needed to get it merged? @jaredpalmer @gsoltis

2022-02-18 20:38 UTC, jaredpalmer approved these changes
I'm fine with this, but when we move to Rust, hopefully the json5 lib we choose will be close as to spec as this library is.

2022-02-18 20:49 UTC, merged