add --silence-cached-logs flag to turbo CLI
vercel/turborepo pull request #822
Opened 2022-03-04 05:44 UTC by chelkyl

* Adds --silence-cached-logs flag to hide logs of all cached tasks output by `turbo run build`
* Preserves the first line of the replayed log stating "cache hit, replaying output ..."

Usage:
`turbo run build --silence-cached-logs`

Without --silence-cached-logs
![image](https://user-images.githubusercontent.com/14041823/156706543-7ca96685-02d9-4e45-a12d-612f3af8af12.png)

With --silence-cached-logs
![image](https://user-images.githubusercontent.com/14041823/156706591-9ec824a1-82ae-429a-a330-987437cb258c.png)

Closes #364

2022-03-04 14:28 UTC, dcherman commented
As a thought, can we also add `turbo logs <hash>` as a way to re-play logs from cached builds?  That way if you do choose to use this flag, you still have a way of inspecting the logs from the completed builds if needed since you'd have the hashes.

2022-03-04 18:05 UTC, weyert commented
I am wondering if something like similar to `docker's  `--progress` flag makes more sense here?
> --progress | auto | Set type of progress output (auto, plain, tty). Use plain to show container output

2022-03-04 22:48 UTC, jlarmstrongiv commented
Wow, this is exactly what I need 😄 can’t wait to see it merged

I think @dcherman’s idea is an interesting.  All logs are saved in the `node_modules/.cache/turbo/<hash>/.turbo/turbo-<command>.log` if you need to find it in the meantime.

2022-03-05 06:45 UTC, chelkyl commented
> I am wondering if something like similar to `docker's `--progress` flag makes more sense here?
> 
> > --progress | auto | Set type of progress output (auto, plain, tty). Use plain to show container output

@weyert That does make a lot of sense! Refactoring.

2022-03-05 08:38 UTC, chelkyl commented
> As a thought, can we also add `turbo logs <hash>` as a way to re-play logs from cached builds? That way if you do choose to use this flag, you still have a way of inspecting the logs from the completed builds if needed since you'd have the hashes.

@dcherman Great idea! I'll see what can be done and what other features this command could have.

2022-03-11 02:06 UTC, weyert commented
Nice, liking this. How can we progress this PR? @gsoltis

2022-03-11 18:23 UTC, gsoltis commented
I like the idea, but I'm a little concerned about the flag name and option values. As I understand it, this is intended to control the behavior of logging when a cache hit occurs. The various options are "replay the logs", "don't replay the logs", and "replay just the first line that shows a cache hit". Does that seem like an accurate summary?

`--progress` on its own doesn't, at least to me, suggest logs behavior. Maybe there's another term we could use? Something like `--cached-logs=[full|silent|name-only]` or something like that? Definitely open to suggestions on this.

2022-03-13 07:02 UTC, chelkyl commented
> I like the idea, but I'm a little concerned about the flag name and option values. As I understand it, this is intended to control the behavior of logging when a cache hit occurs. The various options are "replay the logs", "don't replay the logs", and "replay just the first line that shows a cache hit". Does that seem like an accurate summary?

@gsoltis Previously, the `--progress` option only had 2 modes, "replay the logs" and  "replay just the first line that shows a cache hit".

> `--progress` on its own doesn't, at least to me, suggest logs behavior. Maybe there's another term we could use? Something like `--cached-logs=[full|silent|name-only]` or something like that? Definitely open to suggestions on this.

It was based on what docker provides and I wanted to keep it to a single word but I agree that it could be clearer! I have renamed it to `--output-logs` and added more functionality to control both cached and non-cached task output.
See the updated description and let me know what you think!

2022-03-15 18:00 UTC, gsoltis requested changes
This is coming along!

Can you also resolve any merge conflicts?

2022-03-15 23:30 UTC, chelkyl commented on cli/internal/run/run.go
> +	// Task logs output modes (cached and not cached tasks):
Done! Let me know if you prefer other names/values

2022-03-15 23:30 UTC, chelkyl commented on cli/internal/run/run.go
> +	cachedOutputLogsMode    string
Agreed! Done

2022-03-15 23:30 UTC, chelkyl commented on cli/internal/run/run.go
> +	notCachedOutputLogsMode string
Agreed! Done

2022-03-15 23:31 UTC, chelkyl commented on cli/internal/run/run.go
> +			case strings.HasPrefix(arg, "--output-logs"):
Great catch! Fixed

2022-03-15 23:31 UTC, chelkyl commented on cli/internal/run/run.go
> +				if len(outputLogsMode) > 0 {
That makes sense to me! Done

2022-03-17 22:56 UTC, gsoltis approved these changes

2022-03-17 23:06 UTC, merged

2022-03-17 23:07 UTC, chelkyl commented
Thanks!