Allow concurrency to be set with percentage values
vercel/turborepo pull request #873
Opened 2022-03-12 20:18 UTC by VanTanev

Closes #761

This is modeled after the way that `jest` [allows to set workers by providing a percent with `--maxWorkers=50%`](https://jestjs.io/docs/configuration#maxworkers-number--string).

I've updated Turbo's CLI parsing to accept `--concurrency=50%`. It also supports percentages over 100%, so  `--concurrency=500%` is valid. It uses `runtime.NumCPU()` to get the number of available logical processors, and calculates from there.

Setting the percentage to zero or less is an error. Setting percentage very low, to eg `1%` results in always at least `1` as the value for concurrency.

2022-03-13 15:38 UTC, VanTanev commented
I would also want to work on adding concurrency to the `turbo.json` config file but wanted to submit one PR at a time.

2022-03-16 08:08 UTC, VanTanev commented
@jaredpalmer Is there anything I can do to help move this PR forward? Any changes I should do?

2022-03-21 16:48 UTC, gsoltis requested changes
Overall this looks solid. Just one minor nit.

2022-03-21 20:47 UTC, VanTanev commented on cli/internal/util/parse_concurrency.go
> +			return -1, fmt.Errorf("invalid value for --concurrency CLI flag. This should be a number --concurrency=4 or percentage of CPU cores --concurrency=50%% : %w", err)
Fixed, thanks!

2022-03-21 21:13 UTC, gsoltis commented
@VanTanev Maybe start a discussion for the config file? `turbo.json` is intended to be checked in and shared, and it's not immediately clear to me that everyone would want to default to the same concurrency. Just as an example, I would imagine your CI might want 100% while devs might prefer some headroom left over. My intuition is that this is a setting that is per-machine, like login information. But happy to get input from the community on what would be helpful here.

2022-03-21 21:14 UTC, gsoltis approved these changes

2022-03-21 21:19 UTC, merged

2022-03-22 02:22 UTC, moltar commented
@VanTanev Thanks for this PR!

IMO having an environment config would be more useful that having an entry in the config file.

To me, `turbo.json` config is something permanent, that is project-dependant, and does not change from environment to environment.

But what changes from environment to environment are ... the environment variables 😁 

I might want to run at 100% on CI, and at 50% on my local machine, because it's busy doing other things.

And that's what the environment variables are exactly for! I could even configure my local env permanently via bashrc to _always_ run turbo on 50% settings (again, because I want to use my dev box while it's running builds, regardless of the project). But I _always_ want to take up 100% of the CI.

And if turbo is just another command in a custom build script, then I lose control of the concurrency setting via CLI option and I also cannot change the config from env to env.

2022-03-22 07:22 UTC, VanTanev commented
@moltar Can I add both, with precedence going argument > env > turbo.json?

2022-03-22 08:48 UTC, moltar commented
> Can I add both

@VanTanev I am not the project maintainer, merely the one who raised issue #761 😁 

But I personally see no value in having it inside the config. But to each their own!