feat(turborepo): web ui
vercel/turborepo pull request #8895
Opened 2024-07-31 21:30 UTC by NicholasLYang

### Description

### Testing Instructions

2024-07-31 21:39 UTC, NicholasLYang commented on crates/turbopack-cli/js/package.json
> +    "@vercel/turbopack-ecmascript-runtime": "workspace:*"
For some reason this broke for me

2024-08-12 14:56 UTC, chris-olszewski requested changes
This is awesome. I think we just need to make the refactor the socket handler a little bit so it can continue processing events if a socket ends being slow.

2024-08-12 14:56 UTC, chris-olszewski commented on crates/turborepo-ui/src/wui/mod.rs
> +                        warn!("failed to deserialize message from client: {message_payload}");
I'm getting:
```
failed to deserialize message from client: {"type":"Ack","payload":{}}
```

2024-08-12 14:56 UTC, chris-olszewski commented on crates/turborepo-ui/src/wui/mod.rs
> +            Ok(event) = state.rx.recv() => {
I think we need to handle the case where the Web UI ends up lagging.

2024-08-12 14:56 UTC, chris-olszewski commented on crates/turborepo-ui/src/wui/mod.rs
> +                }
We should drop the lock before we do a serial send.

2024-08-12 14:56 UTC, chris-olszewski commented on crates/turborepo-ui/src/wui/mod.rs
> +    messages: Arc<Mutex<RefCell<Vec<(WebUIEvent, u32)>>>>,
I think we really want to use a new tokio task to manage `messages` state. If the socket is slow on receiving these, we can end up dropping a lot of messages due to how `tokio::broadcast` works.

We're doing a lot of sends on the socket handler task and if one of them ends up being slow we stop moving forward.

2024-08-15 19:13 UTC, NicholasLYang commented on crates/turborepo-lib/src/commands/run.rs
> -            sender.stop();
Kinda. I wanna keep this open even after a run for the web ui. I'll make it only stop the TUI

2024-08-19 21:19 UTC, NicholasLYang commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/vercel/turborepo/8895?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#8895** <a href="https://app.graphite.dev/github/pr/vercel/turborepo/8895?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#8977** <a href="https://app.graphite.dev/github/pr/vercel/turborepo/8977?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @NicholasLYang and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-10 14:19 UTC, chris-olszewski requested changes
Looks like tests are failing.

Aside from that just a minor comment on use of `RefCell` inside of `Mutex`.

2024-09-10 14:19 UTC, chris-olszewski commented on crates/turborepo-ui/src/wui/server.rs
> +    let state = Arc::new(Mutex::new(RefCell::new(WebUIState::default())));
I'm not sure if I understand the use of `RefCell` inside of the `Mutex`. Doesn't the `Mutex` already ensure that there's only ever one access to the underlying data at a time? Why are dynamic borrows necessary inside of the restriction?

If this is necessary a quick comment explaining why would be very appreciated.

2024-09-10 19:30 UTC, chris-olszewski approved these changes

2024-09-10 21:30 UTC, merged