Upgrade docs theme
vercel/turborepo pull request #893
Opened 2022-03-16 17:33 UTC by shuding

This is an example of using the built-in Nextra theme to extend the blog layout. Lots of wrong styling to migrate still.

2022-03-22 17:42 UTC, jaredpalmer commented
@shuding what additional steps do I need to take to push this through goal line

2022-03-24 16:50 UTC, jaredpalmer commented
Made some homepage tweaks here: https://github.com/vercel/turborepo/pull/931

2022-03-24 17:31 UTC, jaredpalmer commented
Done

2022-03-24 18:37 UTC, jaredpalmer requested changes

2022-03-24 18:37 UTC, jaredpalmer commented on docs/theme.config.js
>    github: "https://github.com/vercel/turborepo",
The github link in the nav goes to nextra right now

2022-03-25 02:08 UTC, shuding commented
Missing x-padding here:

![508DC39C-CEF9-46CF-9E54-1E49FBD60447](https://user-images.githubusercontent.com/3676859/160040499-c663d1d1-b904-4d0b-b69b-680673ac9565.png)

2022-03-25 14:06 UTC, merged