Document --filter
vercel/turborepo pull request #914
Opened 2022-03-21 19:07 UTC by gsoltis

- [x] Adds the CLI reference docs for `--filter`
 - [ ] Updates the scoping page to use `--filter`

2022-03-24 23:20 UTC, gaspar09 commented
Are these ready to go?

2022-03-24 23:22 UTC, gsoltis commented
@gaspar09 I think we're waiting for `1.2.0` release

2022-04-04 23:18 UTC, jaredpalmer requested changes

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +You can match packages by name, directory, include dependents/dependencies, and by changes
```suggestion
You can filter packages by name, directory, include dependents/dependencies, and by changes
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +are run first, according to the pipeline specification in [`turbo.json`](/docs/reference/configuration#pipeline).
```suggestion
are run first, according to the `pipeline` specification in [`turbo.json`](/docs/reference/configuration#pipeline).
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +Filter syntax is based on `pnpm`'s filter syntax.
```suggestion
Turborepo's filter syntax is based on pnpm's filter syntax, so it should feel familiar to pnpm users. 
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +### Package specifier - Glob match package names
```suggestion
### Filter by package
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +### Dependents specifier - Include dependents of matched packages
```suggestion
### Include dependents of matched packages
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +### Dependencies specifier - Include dependencies of matched packages
```suggestion
### Include dependencies of matched packages
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +### Directory specifier - Match a directory or directory tree
```suggestion
### Filter by directory or directory tree
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +### Commit specifier - Match changed packages
```suggestion
### Filter by changed packages
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +### Exclusion specifier - Exclude matched packages
```suggestion
### Excluding packages
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/meta.json
> -  "scopes": "Scoped Tasks",
**addition:** Need to add 301 redirect in `next.config.js`

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/features/filtering-packages.mdx
> +[`pnpm`](https://pnpm.io/filtering)
```suggestion
[pnpm](https://pnpm.io/filtering)
```

2022-04-04 23:18 UTC, jaredpalmer commented on docs/pages/docs/reference/command-line-reference.mdx
> +[Filter syntax](/docs/features/filtering-packages) is based on `pnpm`'s filter syntax.
```suggestion
For more detailed information about the `--filter` flag and filtering, refer to the [dedicated page in our documentation](/docs/features/filtering-packages)
```

2022-04-05 00:01 UTC, jaredpalmer requested changes

2022-04-05 00:01 UTC, jaredpalmer commented on docs/next.config.js
> +        destination: "/docs/features/filtering-packages",
Let's change url to just `filtering`

2022-04-05 00:03 UTC, jaredpalmer commented
**suggestion/addition:** let's add a `<Callout>` about how legacy `--scope` is going to be deprecated, but is equivalent to `--filter=XXXXXX` for compatibility as of `turbo@1.1.2+`

2022-04-05 00:10 UTC, gsoltis commented
Re: deprecation, `--scope`, `--since`, `--no-deps`, and `--include-dependencies` (but not `--ignore`) are all technically deprecated.

2022-04-05 00:13 UTC, jaredpalmer commented
Then we should make a little "Deprecated in `1.2.x`" red bubble or `<Deprecated />` like we have for `<Beta>` in Remote Caching and add it to all of the deprecated flags

2022-04-05 05:04 UTC, megbird reviewed
Added some non-blocking comments on the overall organization 😄

2022-04-05 05:04 UTC, megbird commented on docs/pages/docs/features/filtering.mdx
> +### Examples
It seems like these examples might be better divided up in the sections that are the most relevant ☝️ just so the usage and examples are closer together.

2022-04-07 09:46 UTC, weyert commented
How would you rewrite this command to use `--filter` to avoid the deprecated arguments?
`turbo run build --cache-dir=.turbo-cache --include-dependencies --no-deps` or
`turbo run build --cache-dir=.turbo-cache --include-dependencies`

Maybe worth it to add these to the docs or in the blog post?  Also posted this question in the blog post PR

2022-04-07 20:48 UTC, jaredpalmer approved these changes

2022-04-07 20:49 UTC, merged