chore(examples): Remove spare dependencies from basic example.
vercel/turborepo pull request #9516
Opened 2024-11-25 20:24 UTC by anthonyshew

### Description

### Testing Instructions

2024-11-25 20:31 UTC, chris-olszewski requested changes
If we're shipping a pnpm 9 lockfile we should bump the default package manager to match the version used to create the lockfile: https://github.com/vercel/turborepo/blob/9db0da44c87ab5f9c9060884dd28ff2638d6d84e/examples/basic/package.json#L15

2024-11-25 20:41 UTC, chris-olszewski approved these changes

2024-11-25 20:51 UTC, merged

2024-12-09 03:00 UTC, vincenthsh commented
I noticed the examples do not use `.nvmrc` or `.node-version` or `mise.toml` or `.tool-versions` (lol), however on Node v20, eslintv9 requires `20.9.0` or above

2024-12-09 03:22 UTC, anthonyshew commented
[The `engines` field](https://github.com/vercel/turborepo/blob/a1db09a70b03e75097dafd65dddd775567b628dd/examples/basic/package.json#L17) covers this but looks like we're still keeping a minimum of 18. We can update this!