feat: boundaries
vercel/turborepo pull request #9634
Opened 2024-12-19 17:06 UTC by NicholasLYang

### Description

### Testing Instructions

2025-01-02 22:30 UTC, NicholasLYang commented on crates/turborepo-lib/src/boundaries.rs
> +        for (package_name, package_info) in packages {
We could consider parallelizing this, but it's not *that* slow right now (7 seconds for running in `turborepo` on release mode)

2025-01-02 22:30 UTC, NicholasLYang commented on crates/turborepo-lib/src/boundaries.rs
> +                "**/*.svelte".parse().unwrap(),
would love a canonical list of all possible `js` extensions! I might have missed one

2025-01-02 22:30 UTC, NicholasLYang commented on crates/turborepo-lib/src/boundaries.rs
> +            &["**/node_modules/**".parse().unwrap()],
We could leave this up to the `gitignore` check further down, but even recursing into node_modules is rough. In the future we should have a smart filtering mechanism to prevent recursion into directories that are ignored

2025-01-02 22:30 UTC, NicholasLYang commented on crates/turborepo-lib/src/boundaries.rs
> +            let comments = SingleThreadedComments::default();
there's some boilerplate that is repeated between tracer and boundaries, we could deduplicate but imo it's not critical

2025-01-02 23:05 UTC, anthonyshew commented on crates/turborepo/tests/snapshots/boundaries__boundaries_get_boundaries_lints_(npm@10.5.0).snap
> +          "message": "cannot import file `../../packages/another/index.jsx` because it leaves the package",
Nitpick: I'd like to make a move towards writing sentences with capital letters and punctuation for our human-readable errors (including sentence fragments) when we can.

```suggestion
          "message": "Cannot import file `../../packages/another/index.jsx` because it leaves the package.",
```

2025-01-03 15:03 UTC, chris-olszewski requested changes
Mostly small things. Want to verify the test fixture is correct and we're not hitting NPM

2025-01-03 15:03 UTC, chris-olszewski commented on crates/turborepo-lib/src/boundaries.rs
> +        let repo = Repository::discover(&self.repo_root()).ok().map(Mutex::new);
Might be worth calling this for each package instead of the `Mutex` locking overhead. Not for this PR, just future perf work.

2025-01-03 16:19 UTC, NicholasLYang commented on crates/turborepo/tests/snapshots/boundaries__boundaries_get_boundaries_lints_(npm@10.5.0).snap
> +          "message": "cannot import file `../../packages/another/index.jsx` because it leaves the package",
lol Rome had the opposite style guide, so still doing that. It is a little tricky when we're nesting errors cause then we can end up with multiple periods and capitals

2025-01-03 16:22 UTC, NicholasLYang commented on crates/turborepo-lib/src/run/summary/page.rs
> +    pub fn render_html(&self) -> Result<String, Error> {
Oops! This slipped in, removing

2025-01-03 16:23 UTC, NicholasLYang commented on crates/turbo-trace/src/import_finder.rs
> +pub enum ImportType {
Yep! I can write a doc comment for that

2025-01-03 16:37 UTC, NicholasLYang commented on crates/turborepo-lib/src/boundaries.rs
> +        let repo = Repository::discover(&self.repo_root()).ok().map(Mutex::new);
I tested the mutex and at least in a naive hyperfine benchmark, it doesn't change performance at all

2025-01-03 16:38 UTC, NicholasLYang commented on crates/turborepo-lib/src/boundaries.rs
> +        let repo = Repository::discover(&self.repo_root()).ok().map(Mutex::new);
I think if we end up testing packages in parallel it will have an effect, but tbd

2025-01-03 21:15 UTC, NicholasLYang commented on turborepo-tests/integration/fixtures/boundaries/turbo.json
> +{}
yes, I don't think we have support for creating a `Run` without a turbo.json. And eventually boundaries should require the `boundaries` key

2025-01-03 21:16 UTC, NicholasLYang commented on crates/turborepo-lib/src/query/mod.rs
> +                result.emit();
yep, to match the tracing logic for `dependencies`

2025-01-08 17:06 UTC, chris-olszewski requested changes
Only blocker is that we're still depending hitting NPM when fetching the `util` dependency for `another` package in the test fixture.

2025-01-08 17:06 UTC, chris-olszewski commented on crates/turborepo-lib/src/query/mod.rs
> +                result.emit();
Out of scope for this PR, but this feels weird to me. What's the intended use of this info? Should it be output by default or gated behind a trace/debug level log?

2025-01-21 17:13 UTC, chris-olszewski approved these changes

2025-01-22 07:47 UTC, merged